### PR TITLE
Fix error "unexpected duplicate task: CompileXIB " when archiving 

### PR DESCRIPTION
**Pull request by phucnm**
Fix error "unexpected duplicate task: CompileXIB " when archiving with New Build System Xcode 9.

Solution: Put XIB file into another folder whose name is not "Source" - "Resource" in my PR

Reference: https://github.com/CocoaPods/CocoaPods/issues/7079

### CODE REVIEW

**Comment by 1bannamgiauten** [comment]
thanks 👍

**Comment by 1bannamgiauten** [comment]
I think we should update .podspec file like this:

```
core.source_files = ['Source/*.swift']
core.resources = 'Resource/*.xib'
```

screen shot 2017-11-28 at 5 13 28 pm

**Comment by m-revetria** [comment]
Thank you guys for your help, I just updated the PR with @1bannamgiauten comment

**Comment by DenHeadless** [comment]
Actually, this still fails to compile under Xcode 9 new build system and using CocoaPods installation method.

I'm not a user of this library, just found this issue by googling the same problem for XLPagerTabStrip library and this CocoaPods issue - https://github.com/CocoaPods/CocoaPods/issues/7079.

The problem is not about folders, but in that xib file is getting included in Compile Sources build step of CocoaPods project. It is correct that xib was moved to `core.resources`, but it also needs to be removed from here: https://github.com/xmartlabs/XLActionController/blob/master/XLActionController.podspec#L16

This should read like so:

```ruby
core.source_files = ['Source/*.swift']
```

**Comment by phucnm** [comment]
@DenHeadless Thanks! I agree! 

Sorry I did not to notice this thread's notification.

The solution should be specifying source file types rather patchy fixes 😆

**Pull request merged**
