### PR TITLE
Update for Xcode 11.0 beta 5

### PR DESCRIPTION
**Pull request by Puasonych**
Hello! 👋
An error appears when building in Xcode 11:
```
Command CompileXIB failed with a nonzero exit code
```

This problem was solved by removing `customModuleProvider` (i.e. `Inherit Module From Target`) for cells in xib files. 🤗

### CODE REVIEW

**Comment by BSFishy** [comment]
Thanks for the fix! This worked for me.

**Comment by lakecountypassage** [comment]
I didn't use your commit, but I manually changed the file in XCode and it worked, thank you! It would be nice to have this merged before iOS13 is released

**Comment by eastsss** [comment]
can we have this merged? this is critical because it's impossible to compile the pod without this using Xcode 11

**Comment by jimmyhoran** [comment]
> can we have this merged? this is critical because it's impossible to compile the pod without these changes if you use Xcode 11

Agreed. Would be great to get this fix merged in.
Anybody able to provide an indication of when this is likely to be merged?

**Comment by codingrhythm** [comment]
Yeah, we really need to get this merged for iOS 13 release.

**Comment by cassianodialpad** [comment]
@mtnbarreto up! =)

**Comment by Puasonych** [comment]
@mats-claassen thank you! 😜
Maybe you should upgrade to 5.0.1? So it will be more beautiful in podfile. 🤗

**Comment by Puasonych** [comment]
@mats-claassen Well, the "Xcode 11 GM Seed" is already released. It usually doesn't change much 🙃There are usually only bug fixes 🤷🏿‍♂️
However, here you have to make a decision 😊

**Comment by cassianodialpad** [comment]
For extra information: I've tested it with XCode 11 GM seed, works fine.

**Pull request merged**
