### PR TITLE
default implementation of insetForSectionAt, UICollectionViewDelegate…

### PR DESCRIPTION
**Pull request by loryhuz**
…FlowLayout method

We should be able to define different inset for section in our ActionController subclasses. Actually it's only possible to set a common inset for all section. So I just added a default implementation of the corresponding delegate method in ActionController, then we can override it in our custom subclasses.

### CODE REVIEW

**Comment by m-revetria** [comment]
Hi @loryhuz thanks for your contribution!

I tried the change you proposed and looks good to me. Just one thing, the Tweetbot example has a small detail, checkout the images below. You can fix it by overriding the function you added in `DynamicsActionController` and returning `UIEdgeInsets(top: 0, left: 0, bottom: 6, right: 0)` instead of `UIEdgeInsets.zero`.

If you can fix it I'll very glad to merge this PR.

| Tweetbot example before PR | Tweetbot example after PR |
|------------------------------|-----------------------------|
|tweetbot_example_before|tweetbot_example_after|

> Notice how the cancel cell is overlapping the translate cell in the image on the right

**Comment by loryhuz** [comment]
Hi ! Yes sure, I'll do it asap ;)

**Comment by loryhuz** [comment]
Hi @m-revetria, sorry for the long wait. I was on it today, I also changed the way contentHeight is calculated in dynamics controller, otherwise you would need to set both delegate section inset method + collectionViewLayout.sectionInset to get it displayed correctly. Now it's should be fine !

Thx

**Comment by m-revetria** [comment]
Hi @loryhuz thanks for your time fixing the comments. I made a small change in order to return the collection view layout's section inset as default value instead of `UIEdgeInsets.zero`.

I merge this after CI finishes

**Comment by mtnbarreto** [comment]
@m-revetria let's get merged this! I just reviewed it and it seems ok to me.

**Comment by loryhuz** [comment]
Hi guys,
I'm here to help if needed, it would be cool to merge this if it's ok for you 👍

**Comment by mtnbarreto** [comment]
@loryhuz Thanks for contributing!

**Pull request merged**
